### ISSUE TITLE
ident Command fails with 500 error if opt= not specified by client.

### ISSUE THREAD

**Issue by wuftymerguftyguff** [TechLiam/SQRL-For-Dot-Net-Standard#16]
**Describe the bug**
ident Command fails with 500 error if opt= not specified by client.

**To Reproduce**
Send an ident request with no opt= parameter

**Expected behavior**
opt is not mandatory, request should proceed as per sqrl protocol

**Screenshots**
NA

**Desktop (please complete the following information):**
 iOS client ( no yet released)

**Smartphone (please complete the following  iOS client ( no yet released)

**Additional context**

**Comment by TechLiam** [comment]
This bug was discussed in detail on Slack but resulted in opt been identified as the issue

As the spec says this

> Every client query must contain, at minimum, the following three name=value pairs:
> 1. “client”: A base64url-encoded list of client parameters. The details of all client parameters is
detailed below.
> 2. “server”: The base64url-encoded data returned by the server in response to the previous client
query, if any, or the sqrl:// URL if this is the client’s initial query.
> 3. “ids”: The base64url-encoded signature of the concatenated client and server values above, in
that order. In this instance, the signature’s key is the per-site private key corresponding to the
per-site public key provided by the client within its parameter list contained in the “client” data. 

it is clear that opt is not mandatory and should not be handled as such

**Comment by TechLiam** [comment]
This has now been fixed as of 1.3.0
